### ISSUE TITLE
collections Mapping deprecated

### ISSUE THREAD

**Issue by hwreeves-USGS** [usgs/modflow-setup#41]
collections Mapping is deprecated in python 3.9; 

can fix the problem in utils.py by changing the first import line to:
from collections.abc import Mapping

and in lines 33 and 34 change the isinstance(d, collections.Mapping) to just (d, Mapping)

I was worried I'd mess up something if I tried to push the change and thought this might be faster for such a small fix.

**Comment by aleaf** [comment]
@hwreeves-USGS  this should be fixed now.
