### ISSUE TITLE
question about make_irch in discretization.py

### ISSUE THREAD

**Issue by hwreeves-USGS** [usgs/modflow-setup#54]
I was working on the recharge package and getting a strange irch domain.

In the following code block from discretization.py (lines 468-475), shouldn't
the inactive and pass through get set back to -2 and not 0?

I am getting the min_layer for recharge as the top layer, 0, so irch
is all 0 and 9999 but then the 9999s get set to zero and the whole
thing incremented to 1.  If you set the 9999s to -2 and then increment
the irch will be either 1 or -1.  
~~~
# now reset all the inactive/passthrough values to large positive to not mess up min calc
    idm_lay[idm_lay==-1] = 9999
    # find min active layer
    irch = np.min(idm_lay, axis=0)
    # set all inactive and pass through back to -1
    irch[irch==9999] = 0
    irch += 1 # set to one-based
    return irch
~~~

**Comment by aleaf** [comment]
Hi @hwreeves-USGS, I'm not what the comment about -1 means (might be a typo), but if I'm reading this right, the cells that are still == 9999 after taking the minimum along axis one are at locations that are inactive in all layers. So the value of irch shouldn't matter (there is no model solution at those locations). Currently irch is being set to 1 at inactive locations (1 is the default value for irch). I could maybe see using another value to differentiate between active and inactive locations, but not sure if MODFLOW would allow irch values outside of the range of layers.

**Comment by hwreeves-USGS** [comment]
@aleaf I'm probably misunderstanding irch, guess I should read the manual...

**Comment by aleaf** [comment]
Hi @chanse-ford if you think this isn't working right for you case, can you zip up a minimum working example and send it to me? Might be easier to look at it in the debugger.

**Comment by chanse-ford** [comment]
Sure. I'm incorporating some new layer data I just received, so I'll send you something here in the next day or two when I've preprocessed everything and have setup_model.py ready to run again.
